package mocks

import (
	"github.com/fleetdm/wordgame/internal/store"
	"github.com/stretchr/testify/mock"
)

// MockGameStore is an autogenerated mock type for the GameStore type
type MockGameStore struct {
	mock.Mock
}

func (m *MockGameStore) SaveGame(game *store.Game) error {
	args := m.Called(game)
	return args.Error(0)
}

func (m *MockGameStore) LoadGame(id string) (*store.Game, error) {
	args := m.Called(id)
	return args.Get(0).(*store.Game), args.Error(1)
}
